version = 1

exclude_patterns = [
	"prisma/_queries/**",
	"prisma/data-migrations/**",
	"prisma/migrations/**",
]

[[analyzers]]
	name = "secrets"

[[analyzers]]
	name = "javascript"

	[analyzers.meta]
		environment = ["browser", "nodejs"]
		plugins     = ["react"]

		# [[transformers]]
		# name = "prettier"
