name: Lint & format

on:
  push:
    branches-ignore: [dev, main, renovate/*]

jobs:
  lintformat:
    # env:
    # GITHUB_TOKEN: ${{ secrets.GH_ACT_PAT }}
    name: 'Lint & format'
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_KEY }}
          git_user_signingkey: true
          git_config_global: true
          git_commit_gpgsign: true

      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
          # standalone: true

      - name: Install Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Lint projects
        run: pnpm lint:fix
        if: always()
        id: lint

      - name: Format projects
        run: pnpm format
        if: always()
        id: format

      # Commit changes
      - name: Commit changed files
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        if: always()
        with:
          message: 'chore: lint & format'
          commit: --signoff --no-verify
          committer_name: InReach [bot]
          committer_email: 108850934+InReach-svc@users.noreply.github.com
          author_name: InReach [bot]
          author_email: 108850934+InReach-svc@users.noreply.github.com
